### ISSUE TITLE
Create initial project structure

### ISSUE THREAD

**Issue by jeyvison** [eclipse-ee4j/starter#1]
As i raised the point in the dev list, i'm planning to send a very basic structure to the initial commit of this project.  We can always base our logic in the microprofile generator if we think it's worth

**Comment by rdebusscher** [comment]
I would create a similar structure as the Microprofile generator (and using templating to generate the content)

But I would like to create a multimodule project structure with core, frontend and REST API (as the MP starter was initially before the initial upload)

**Comment by jeyvison** [comment]
Hello @rdebusscher .
Yeah, the idea is still use templating to generate the examples as MP generator does .

I have no problem in setup a multimodule project. I think we can do it in the first commit.

**Comment by jeyvison** [comment]
Thinking a little bit more about this, @rdebusscher , do you know if there is a reason why they rolled it back from multimodules? Maybe it's worth for us to understand why they did it and analyze if we should go the same way or not. I will try to find out what happened.

**Comment by rdebusscher** [comment]
The decision to use a single project at the start of MP starter was made out of simplicity. At that point, only a JSF frontend was planned and thus no separate core module needed.

The idea of accessing the starter via REST API came a year later.

**Comment by jeyvison** [comment]
Got it. I'll create the multimodule structure then. Since it's the beggining of the project that's not much risky if we decide to remove one of them

**Comment by jeyvison** [comment]
as of https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21695, i'll checkout the initial structure to the repo and close this issue. With this we will be able to fork the repository.
