### ISSUE TITLE
Add support for Liberty

### ISSUE THREAD

**Issue by m-reza-rahman** [eclipse-ee4j/starter#112]
@rokon12 is working on this.

**Comment by rokon12** [comment]
I will add OpenLiberty for the [minimal-starter](https://github.com/eclipse-ee4j/starter/tree/master/minimal-starter) soon, maybe at the end of the week.  The [rest-starter](https://github.com/eclipse-ee4j/starter/tree/master/rest-starter) have a slight issue in testing, which I will discuss with @m-reza-rahman

**Comment by m-reza-rahman** [comment]
Addressed by #170.
