### ISSUE TITLE
Glassfish in Windows 

### ISSUE THREAD

**Issue by jeyvison** [eclipse-ee4j/starter#121]
The way we're generating glassfish today we're unzipping it into /tmp directory what will (probably) cause errors when the user runs the project in Windows.

I'm creating this issue so we can discussewhat's the best path to set Glafissh to, or if we will drop support for Windows for now, or if we will be SO-aware during the project generation, etc...

**Comment by m-reza-rahman** [comment]
/tmp works fine on Windows (I tested it). Is there a specific problem you ran across?

**Comment by jeyvison** [comment]
No, to be honest i didn´t test it , it was just an assumption. I'll close the issue then. Thanks :)
