### ISSUE TITLE
Starting Payara Issue

### ISSUE THREAD

**Issue by Osahamed** [eclipse-ee4j/starter#134]
Starter Page shows command to start Payara Micro 
`mvn clean package payara-micro:start`
but the plugin is not in the generated pom

**Comment by m-reza-rahman** [comment]
Could you kindly provide the exact steps to reproduce? I assume you ran one of the archetypes first and chose Payara?

**Comment by m-reza-rahman** [comment]
This should all be sorted by: https://github.com/eclipse-ee4j/starter/pull/172. Can you please check the master branch content and probably close this?
