### ISSUE TITLE
Add more validation on the UI field: groupId

### ISSUE THREAD

**Issue by IvoNet** [eclipse-ee4j/starter#149]
Add validation to the groupId field in the starter UI

GroupId should only allow:

- lowercase names
- names starting with [a-z]
- dot as separators
- no hyphens ('-') but underscores ('_')
- no spaces
- etc.
see also here: [guide-naming-conventions](https://maven.apache.org/guides/mini/guide-naming-conventions.html)

**Comment by geziefer** [comment]
I could do this together with #274

**Comment by geziefer** [comment]
artifactId must start with a letter and then contain any number of letters, digits or underscore - the following regex was used: "^[a-zA-Z][a-zA-Z0-9_-]*$"/>

This was addressed in PR #292

**Comment by m-reza-rahman** [comment]
Fixed.
