### ISSUE TITLE
Add more validation on the UI field: artifactId

### ISSUE THREAD

**Issue by IvoNet** [eclipse-ee4j/starter#150]
Add validation to the artifactId field in the starter UI

ArtifactId should only allow:

- lowercase names
- names starting with [a-z]
- hyphens ('-') but no underscores ('_')
- no spaces
- etc.

see also here: [guide-naming-conventions](https://maven.apache.org/guides/mini/guide-naming-conventions.html)

**Comment by geziefer** [comment]
I could do this together with #274

**Comment by geziefer** [comment]
groupId satisfies java package naming which must start with a letter followes by any number of letters, digits or underscore and then any number of similar parts separated by dot - the following regex was used: "^[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)*$"
This was addressed in PR #292

**Comment by m-reza-rahman** [comment]
Fixed.
