### ISSUE TITLE
Add more validation on the UI field: version

### ISSUE THREAD

**Issue by IvoNet** [eclipse-ee4j/starter#151]
Add validation to the version field in the starter UI

'version' should only allow e.g.:

- 1.0.0-SNAPSHOT
- 1.0.0
- 1.0
- 1.2.999-SNAPSHOT
- 1.0.0-RC2

see also here: [guide-naming-conventions](https://maven.apache.org/guides/mini/guide-naming-conventions.html)

Default value should be 1.0.0-SNAPSHOT (as it already is)

**Comment by rokon12** [comment]
Do we use a regex for this? or use a dropdown of this fixed value.

**Comment by rokon12** [comment]
Example - 

`^(?:[1-9]\d*)(?:\.(?:0|[1-9]\d*))*(?:-(?:SNAPSHOT|RC\d+))?$`

**Comment by m-reza-rahman** [comment]
Yes, a regular expression should be good.

**Comment by jeyvison** [comment]
I'm not sure if we should add a validation for this. 

Doing so will force the user to use the pattern we defined instead make it free for them use the version field as they see fit.  After all, the name guide is a convention, not a rule.

**Comment by m-reza-rahman** [comment]
Agreed. I think this is a very low priority we should look at much later.

**Comment by geziefer** [comment]
I could do this together with #274

**Comment by geziefer** [comment]
@m-reza-rahman For clarification: Should the 3 validation tickets apply to UI only or already be incorporated in archetype?
My personal suggestion is to go with UI only, as this is our provided convenient access to the archetype, but if someone uses purely the archetype, he could input whatever he wants as Maven coordinates.

**Comment by m-reza-rahman** [comment]
I think that’s fine. To be honest I don’t think these validations are super important. They are a nice to have.

**Comment by geziefer** [comment]
This ticket should be closed as "won't do".
It was already agreed when enhancing the UI that version is not necessarry. It is unlikely, that the user needs to have something different than the default and is able to change this very easy without any effect to other files than the pom.

**Comment by m-reza-rahman** [comment]
Agreed. Closing for now.
