### ISSUE TITLE
Add support for Zip download in Starter UI

### ISSUE THREAD

**Issue by m-reza-rahman** [eclipse-ee4j/starter#153]
The Starter UI will take higher level functional inputs (such as Jakarta EE version, Java SE version, Jakarta EE profile) and generate a Zip file that the user downloads containing the actual generated code example.

**Comment by m-reza-rahman** [comment]
The current consensus is that this is a priority item to be implemented soon. Concise input from key community members can be found here: https://docs.google.com/spreadsheets/d/1bthiYVjX_UK7Xp2qQmq93awPwVhVCDnprGdzeMtv_ow/edit?usp=sharing. A discussion thread on the mailing list can be found here: https://www.eclipse.org/lists/starter-dev/msg00182.html.

**Comment by OndroMih** [comment]
Support for command output is already in the current Starter UI, so there's no need to do anything to keep it. We just need an additional button to download the ZIP.

I wrote a Java app that generates a ZIP file from a maven archetype. I plan to donate the code to the Starter and so that we can simply generate the ZIP from the archetype when a user presses the Download ZIP button.

**Comment by m-reza-rahman** [comment]
I think this is a factor worth discussing further once we go through the major decisions. The problem is what to do for Gradle, if there is a CLI what does that do/how does it look like and whether there is really sufficient value/support for this option in the overall context. There is very clearly sufficient support for the Zip option.

**Comment by OndroMih** [comment]
I've raise https://github.com/OndroMih/jakartaee-starter/pull/2 PR where I ported my older code to generate a ZIP file from a maven artifact and improved it. Once we deploy the servlet somewhere, we can add a button to generate the ZIP like in this PR: https://github.com/eclipse-ee4j/starter/pull/156

The current EE Starter page is running on github pages, there's no way to deploy a servlet there. We'll need to sort out where to deploy the backend app before we update the UI.

**Comment by m-reza-rahman** [comment]
I’ve secured a permanent App Service JBoss EAP instance for this project. Would you like to get the Servlet running there? If so, I can give you the basic details and give you the credentials offline. Also, because it’s a Jakarta EE runtime, you aren’t limited to just Servlet. If you like, you can use REST, Faces, etc. In fact, it may be a good gesture to do so since we are trying to promote Jakarta EE after all.
    
  

 From: Ondro Mihályi ***@***.***>Sent: Thursday, November 24, 2022 3:13 AMTo: eclipse-ee4j/starter ***@***.***>Cc: Reza Rahman ***@***.***>; Author ***@***.***>Subject: Re: [eclipse-ee4j/starter] Add support for Zip download in Starter UI (Issue #153) 
I've raise OndroMih#2 PR where I ported my older code to generate a ZIP file from a maven artifact and improved it. Once we deploy the servlet somewhere, we can add a button to generate the ZIP like in this PR: #156
The current EE Starter page is running on github pages, there's no way to deploy a servlet there. We'll need to sort out where to deploy the backend app before we update the UI.

**Comment by OndroMih** [comment]
Sure, I'll connect with oyu, @m-reza-rahman . I agree it would be good to use something else than just Servlet but the instructions in the README mention deployment on Tomcat, so I stayed with plain Servlet for the initial solution. It would be nice to rewrite it to JAX-RS, which would simplify the code a bit. But it's not necessary, it's a very simple servlet.

**Comment by m-reza-rahman** [comment]
Great! Forgot to mention - feel free to just connect with Bazlur too. He has been working on this part more so than me. I have also connected him to the right people on the App Service team, who are actually financially sponsoring the hosting.

**Comment by OndroMih** [comment]
The service is now deployed at https://jakarta-starter-ui.azurewebsites.net/download.zip?archetypeGroupId=org.eclipse.starter&archetypeArtifactId=jakartaee10-minimal&archetypeVersion=1.1.0&groupId=ee.omnifish&artifactId=sample&profile=core-api&version=1.0.0-SNAPSHOT, thanks to @rokon12.

Later we should add some caching because generating the ZIP file is pretty slow (around 5 seconds).

**Comment by m-reza-rahman** [comment]
The need for caching I had already discussed with @rokon12. It should not be too difficult to implement and we can request sufficient memory on the hosting instance (in fact we can generally ask for an appropriate amount of resources including scaling to demand).

**Comment by IvoNet** [comment]
I think caching is actually rather difficult.
As we put specific artifactId and groepId and package structure in there and the like.
How useful would caching be in that case? only for the same request right? and how often do you think that will happen? I would guess that except for the demo project (default) just about never right?
When would a cache be invalid or valid?

There are only two hard things in Computer Science: cache invalidation and naming things.

-- Phil Karlton


Ivo.

**Comment by m-reza-rahman** [comment]
I suggest simply having some logging in place to track cache hits/misses over time. If it turns out there are too many misses, we could simply remove caching later on. If it turns out the hits are good enough (which I suspect will be the case as many will simply accept the defaults), it is definitely a worthwhile improvement. That said I will review the code together with @rokon12 and see if there is scope for other improvements and we can definitely ask for more compute resources.

**Comment by OndroMih** [comment]
If I'm not wrong, the resulting ZIP file doesn't change for the same archetype parameters. E.g., for a specific archetype (groupId, artifactId and version), specific EE profile, and specific target project coordinates, the ZIP will be always the same. 

The only issue is that users will tend to define their own target coordinates and then a new ZIP will need to be generated. So caching wouldn't help when a new user comes and defines their own coordinates. We can either cache everything (just in case the same user would generate the same things multiple times) and evict from the cache after a day or so, or we can only cache for the default target coordinates.

If default target coordinates are used, caching reduces the time greatly and there's no need to invalidate the cache. And I bet there will be many users that would just leave the default coordinates there just to see what's generated in the ZIP or plan to change the coordinates manually later. This is how I often use MP and Spring starters when I just want to check how the code looks like and I don't want to use in a real project.

**Comment by m-reza-rahman** [comment]
We could indeed just have a pre-populated static cache of the defaults. That’s the assumption anyway.

**Comment by IvoNet** [comment]
Agreed for the defaults this is totally fine and viable. I did not realise it would be used that much. I always tend to define all the parameters to my own needs and that would make them quite unique.
But then I would probably use the command line generator :-)

**Comment by m-reza-rahman** [comment]
Please note that the current consensus is to implement the Starter UI in JSF and to host on App Service JBoss EAP (please see: https://www.eclipse.org/lists/starter-dev/msg00282.html for reference). @rokon12 is working hard on these changes. I am sure he would be happy if other folks helped, even if just review for now.

**Comment by m-reza-rahman** [comment]
Initial version complete.
