### ISSUE TITLE
Include runtime in generated code examples

### ISSUE THREAD

**Issue by m-reza-rahman** [eclipse-ee4j/starter#154]
Include a runtime reference of the user's choice directly into the POM of the generated code example. This allows for running the example code from Maven without any further configuration. 'mvnw' is included in the code example such that it is not necessary to have Maven installed. This approach is already implemented to some extent for GlassFish, Payara, TomEE and WildFly: https://github.com/eclipse-ee4j/starter/tree/master/minimal-starter. This allows for the possibility to vary the generated code example slightly per runtime if needed. It also allows for the inclusion of a working Dockerfile in the code example as well as a generated README specific to the runtime.

By default, the user need not choose a runtime, in which case a runtime will not be included. Generic code (likely mostly tested against GlassFish) will be generated in such a case. It is likely some supported runtimes simply do not make it possible to run from Maven without further manual installation/configuration (such as WebLogic and WebSphere Traditional). In such cases, a generated README will still include sufficient instructions to run the code example.

Ideally, each vendor should help implement support for their own runtimes.

**Comment by m-reza-rahman** [comment]
The current consensus is that this is a priority item to be implemented soon. Concise input from key community members can be found here: https://docs.google.com/spreadsheets/d/1bthiYVjX_UK7Xp2qQmq93awPwVhVCDnprGdzeMtv_ow/edit?usp=sharing. A discussion thread on the mailing list can be found here: https://www.eclipse.org/lists/starter-dev/msg00183.html.

**Comment by m-reza-rahman** [comment]
The MicroProfile Starter renders the order of runtime choices randomly each time. We should adopt the same approach to remain as neutral as possible.

**Comment by rokon12** [comment]
Having a runtime is important. 

As @m-reza-rahman  suggested, there may be some merit to the desire to have no runtime. 
One thing we could do is we implement it that way and track usage.

If most people choose a runtime, we could drop the “no runtime” option in the future.

**Comment by m-reza-rahman** [comment]
Indeed. I do suspect "no runtime" is an edge case if the user has a choice. However, we could easily validate/invalidate that hypothesis with actual usage data in the future.

**Comment by m-reza-rahman** [comment]
Addressed by #170.
