### ISSUE TITLE
EE 9.1 artifact uses EE 10-level API dependencies?

### ISSUE THREAD

**Issue by scottkurz** [eclipse-ee4j/starter#167]
Selected
![image](https://user-images.githubusercontent.com/4081634/207930566-6af4256b-1d68-41b1-89d7-910d1fd81d50.png)

and ran generated command:
> mvn archetype:generate -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakartaee9.1-minimal -DarchetypeVersion=1.0.0 -DgroupId=c
om.example -DartifactId=demo2 -Dprofile=web-api -Dversion=1.0.0-SNAPSHOT -DinteractiveMode=false

which results in my pom.xml with dependency:
```xml
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>10.0.0</version>
            <scope>provided</scope>
        </dependency>
```

Looks like a mistake?

**Comment by ivargrimstad** [comment]
Yes, that's a bug. Thanks!

**Comment by scottkurz** [comment]
Works fine with the 'jakarta-starter' archetype with `-DjakartaVersion=9.1` and `-Dprofile=web|full`.  Not sure if the 'jakartaee9.1-minimal' artifact is still relevant (the one in the original comment)

**Comment by m-reza-rahman** [comment]
In the 2.0 release, we have added a deprecation notice to all the redundant artifacts. Once 2.0 is released into Maven Central, the idea is to remove these from the repository.
