### ISSUE TITLE
Update FirstCup tutorial to use this starter

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/starter#184]
I found the firstcup tutorial example includes two archetypes(faces, Jaxrs) and two simple examples. To decrease the maintenance of the Jakarta EE tutorial.

Update the firstcup tutorial to use this starter and deprecated the archetypes in firstcup examples.

* https://github.com/eclipse-ee4j/jakartaee-firstcup
* https://github.com/eclipse-ee4j/jakartaee-firstcup-examples

**Comment by m-reza-rahman** [comment]
Please move this discussion to the platform project mailing list: https://accounts.eclipse.org/mailing-list/jakartaee-platform-dev or issue tracker: https://github.com/eclipse-ee4j/jakartaee-platform/issues. This project cannot implement this change.
