### ISSUE TITLE
Apply Artifact ID to all output

### ISSUE THREAD

**Issue by angayap** [eclipse-ee4j/starter#189]
Hello,
can we point to 
in file
archetype\src\main\resources\archetype-resources\pom.xml
line 53 `<name>${artifactId}</name>`

line 1153 `<finalName>${artifactId}</finalName>`

Tank

**Comment by m-reza-rahman** [comment]
Do you feel this is a high priority? If so, please issue a PR including fixes to the Dockerfile and all documentation. If not, we can get to this when we are able. It's not particularly difficult, but it is a lot of work and I am not sure it's that big a deal.

**Comment by ojuschugh1** [comment]
sir we have to only change name and filename in all pom.xml file in src ?

**Comment by m-reza-rahman** [comment]
As I already mentioned, it's far more than that. The generated Dockerfile and all associated documentation, including generated READMEs will need to be handled. If someone wants to work on this I suggest first adequately understanding the project. Most likely that will take days if not weeks for a newcomer. This is no easy task.

**Comment by ojuschugh1** [comment]
ohh that's why i am it seems so easy i just right now commited it lol :(

**Comment by geziefer** [comment]
I could do this one together with #274

**Comment by geziefer** [comment]
Was addressed in PR #291 
All files now respect the given artifactId, including pom, readme, docker, war
Java package is left unchanged for now, it contains groupId + fix sub package (-> see mailing list discussion, may be changed in different PR)

**Comment by m-reza-rahman** [comment]
Fixed.
