### ISSUE TITLE
Support Specifications

### ISSUE THREAD

**Issue by jeyvison** [eclipse-ee4j/starter#2]
This is the list with specs we should support:

- [x] Activation --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Annotations --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Authentication --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Authorization --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Batch --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Bean Validation --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Concurrency --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Connectors --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] CDI --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Enterprise Beans --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Expression Language --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Interceptors --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] JSON Binding --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] JSON Processing --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Mail --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Messaging --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Persistence --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Restful Web Services -> https://github.com/eclipse-ee4j/starter/issues/4
- [x] Security --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] JSF --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] JSP --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Servlet --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] JSTL --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] Transactions --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] WebSocket --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] XML Binding --> https://github.com/eclipse-ee4j/starter/issues/13
- [x] XML Web Services --> https://github.com/eclipse-ee4j/starter/issues/13

We can create a ticket for each one as we start to work on them.  Not sure if we plan to support all of them.

If you're starting to work in one of them, please create an issue and let us know.  What do you folks think?

**Comment by rdebusscher** [comment]
Hi,

when you say, `specs we should support:` do you mean create an example for it? At least that is how I see it.

But in some cases, one example also covers other topics (which is encouraged to do so in my opinion) like
JSF -> EL and CDI
Security -> Authentication and Authorization

**Comment by jeyvison** [comment]
Hello @rdebusscher 

> when you say, specs we should support: do you mean create an example for it? At least that is how I see it.

Yep, that's what i meant.

> But in some cases, one example also covers other topics (which is encouraged to do so in my opinion) like
JSF -> EL and CDI
Security -> Authentication and Authorization

You are right but i wonder if it makes sense to create examples, for example, for CDI and EL alone.  Probably not but if this is the case we have to make it clear what specs will be covered by an "umbrella" spec

**Comment by jeyvison** [comment]
I removed NoSQL because it's not clear to me if they have a version that can be used. Also, i'm gonna createa differente ticket for the examples,
