### ISSUE TITLE
Footer copyright char displays "&copy;" entity encoding rather than copyright symbol

### ISSUE THREAD

**Issue by scottkurz** [eclipse-ee4j/starter#208]
The footer I see looks like
![image](https://user-images.githubusercontent.com/4081634/225407768-1d5b419e-07d9-4dfd-a281-2b9810b36e2d.png)
on Windows 11, with all three browsers:  Edge, Chrome, Firefox.

**Comment by m-reza-rahman** [comment]
Hi @rokon12, can we address this please? Otherwise I will do it probably over the weekend.

**Comment by rokon12** [comment]
![image](https://user-images.githubusercontent.com/429073/225974144-bfd3914a-5b31-485d-bd2b-7200abf03eee.png)
This has been fixed, I am closing the issue.
