### ISSUE TITLE
Improve look and feel of UI

### ISSUE THREAD

**Issue by kito99** [eclipse-ee4j/starter#248]
Tweak the UI so that it looks a little more slick, and also is easier to read. Also ensure that responsiveness works well on smaller viewport sizes.

Practically this means picking a different PrimeFaces theme and tweaking the CSS.

**Comment by m-reza-rahman** [comment]
Thanks Kito for picking this up. Please do feel free to take a holistic look at things. Making it fit the jakarta.ee site overall may be a good aim too. I am pretty sure it all could use help. Bazlur and I are hardly UI proficient.

**Comment by batashi** [comment]
Hi @kito99 
Sorry for bothering could you look into the below layout? 

![image](https://user-images.githubusercontent.com/6708191/230949496-ad8c7d62-2a07-4452-a160-5b5d48835fe2.png)

layout @ penpot : https://design.penpot.app/#/dashboard/team/4c677aeb-b8cb-800f-8002-56435f50f7a0/projects

please ignore the colors hehe

**Comment by m-reza-rahman** [comment]
Just to be clear, we discussed form input type and layout alternatives on the mailing list. The current focus is look and feel rather than making any changes to layout and form input type.

**Comment by TanjaObradovic** [comment]
I think for this we need to involve Shabnam Mayel also, so look and feel from our  website can be followed. Let me ping her.

**Comment by m-reza-rahman** [comment]
Hi @kito99, any updates on getting the ECA sorted? Maybe @TanjaObradovic could help you with that too?

**Comment by m-reza-rahman** [comment]
Hi @kito99, is this adequately addressed? Should we close it?
