### ISSUE TITLE
Usage reports

### ISSUE THREAD

**Issue by m-reza-rahman** [eclipse-ee4j/starter#250]
Implement ability to generate usage reports (including by feature) on demand, to be shared with appropriate audience (based on agreement with committers and key stakeholders).

**Comment by jeyvison** [comment]
+1 Can azure offer some DB for us so we can save this kind of data or are you thinking about a different way to do this ?

**Comment by m-reza-rahman** [comment]
Right now, just a report based on aggregated logs. A DB just for this is probably overkill.
