### ISSUE TITLE
Enforce More Rigorous Parameter Validation

### ISSUE THREAD

**Issue by scottkurz** [eclipse-ee4j/starter#266]
This is a minor point in and of itself though maybe more interesting to anyone who's thought more about organizing the validation of the various options.

In the groovy script we use this logic to decide whether to delete the Dockerfile

```groovy
private generateDocker(docker, runtime, File outputDirectory) {
    if (docker.equalsIgnoreCase("no")) {
        println "Docker support was not requested"
        FileUtils.forceDelete(new File(outputDirectory, "Dockerfile"))
```

In the README archetype template we use this logic to decide whether to add the docker build/run instructions:

```text
#if ((${docker} == 'yes') and (${runtime} != 'glassfish'))
```

So for someone setting, say,   `-Ddocker=y`   (as opposed to 'yes') they'll get the Dockerfile but not the README instructions. 

Probably most people that are running archetype:generate and would want to use theDocker image are going to know how to build & run it it, so not a huge impact, but still ... possibly worth considering if there's a need and an approach to be more consistent here.

**Comment by m-reza-rahman** [comment]
The docker flag will only accept “yes” or “no” as input (there is input validation in place in the Archetype). Any other input will either be ignored or fail validation. What behavior are you seeing?

**Comment by m-reza-rahman** [comment]
I see the problem. Essentially the validation is only applied interactively and currently can be side-stepped. Weird that Archetypes even allow this. Regardless, I'll fix this by enforcing strict parameter validation in the Groovy script. I'll do this ASAP. The Archetype and UI need some minor work anyway.

**Comment by scottkurz** [comment]
> I see the problem. Essentially the validation is only applied interactively and currently can be side-stepped.

Hadn't appreciated that point either, but yes, exactly, I was doing: `mvn archetype:generate ... -Ddocker=y ....`.

Thanks for looking into this.

**Comment by m-reza-rahman** [comment]
Fixed by: https://github.com/eclipse-ee4j/starter/pull/269
