### ISSUE TITLE
View expiring?

### ISSUE THREAD

**Issue by youngledo** [eclipse-ee4j/starter#271]
<img width="680" alt="image" src="https://github.com/eclipse-ee4j/starter/assets/68590897/488b2f9e-b2fd-4c2a-8885-cfa9c8f9438b">

**Comment by m-reza-rahman** [comment]
Please provide steps to reproduce.

**Comment by youngledo** [comment]
<img width="1070" alt="image" src="https://github.com/eclipse-ee4j/starter/assets/68590897/69936ffe-b1c0-4780-b8a2-180eb54f3917">
Select these and click on Generate

**Comment by m-reza-rahman** [comment]
I cannot reproduce. I have also tried other combinations.

Is it possible you have expired cookies/sessions? What happens when you clear your cache and restart the browser?

**Comment by youngledo** [comment]
Normal after cleaning cache

**Comment by m-reza-rahman** [comment]
This is possibly due to view expiration. Let me look into it. It would be really good to get steps to reproduce if possible.

**Comment by m-reza-rahman** [comment]
I'm saving the state on the client instead of the server for now. That should eliminate most cases where a view would expire. I'll continue to keep an eye on this.

**Comment by m-reza-rahman** [comment]
This appears to be resolved for now.
