### ISSUE TITLE
Add automated testing for UI

### ISSUE THREAD

**Issue by geziefer** [eclipse-ee4j/starter#275]
So far, we don't have a single unit test, not even the src/test folder is there.
There is not much, the ui is doing, but at least some business logic is involved and might break by changes, so we should think of some reasonable tests.

Higher level tests, including UI or generation is so far done manually, but there might also be some cases which might makes sense on top of unit tests, as there is for example validation involved or caching depending on the input.

**Comment by m-reza-rahman** [comment]
Already encapsulated in https://github.com/eclipse-ee4j/starter/issues/185 and https://github.com/eclipse-ee4j/starter/issues/168.
