### ISSUE TITLE
Clarify discrepancies in Maven Archetype Build with some configurations

### ISSUE THREAD

**Issue by Tasnim1147** [eclipse-ee4j/starter#300]
Hi,

We've noticed some discrepancies in the Maven archetype build process for various configurations of Maven Archetype Build. Specifically, there are cases where the build succeeds locally even though it should not when compared to [starter](https://start.jakarta.ee/).  The attached document provides a comprehensive table of all tested configurations, highlighting where these discrepancies occur.
[Validation Cases.xlsx](https://github.com/user-attachments/files/15802773/Validation.Cases.xlsx)

**Comment by m-reza-rahman** [comment]
Looks like one bug is that the Archetype allows using SE 8 with EE 10, at least for Liberty and none.
