### ISSUE TITLE
Fix typo in README.md  

### ISSUE THREAD

**Issue by juliotobias** [eclipse-ee4j/starter#56]
Fix some typos in README file.

**Comment by dgabriel123** [comment]
On it

**Comment by jeyvison** [comment]
Hi @dgabriel123 . Thanks for your help but @juliotobias  is already on it i just forgot to assign him to the task ^^

**Comment by dgabriel123** [comment]
> Hi @dgabriel123 . Thanks for your help but @juliotobias is already on it i just forgot to assign him to the task ^^

Aw ok, thanks for letting me know!

**Comment by jeyvison** [comment]
Thanks to you!
