### ISSUE TITLE
simple-hello.zip does not load

### ISSUE THREAD

**Issue by chrisguindon** [eclipse-ee4j/starter#62]
We are getting a 404 from https://start.jakarta.ee/starter/samples/simple-hello.zip but https://eclipse-ee4j.github.io/starter/samples/simple-hello.zip is working.

Can we update the link for that page to go to https://eclipse-ee4j.github.io/starter/samples/simple-hello.zip?

This was initially reported here:
https://github.com/jakartaee/jakarta.ee/issues/1029

**Comment by jeyvison** [comment]
Looks like the link is already the one from github in the gh-pages branch. Not sure what else should we do. Maybe @ivargrimstad or @TanjaObradovic can help us with this one :)

**Comment by ivargrimstad** [comment]
@jeyvison I guess one way is to hard code the link. The reason why the relative link does not work is that start.jakarta.ee points to eclise-ee4j.githubu.io/**starter**.
