### ISSUE TITLE
Add Starter UI

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/starter#67]
User Input:
- maven coordinates (group id, artifact id)
- Jakarta EE version (8, 9 and 9.1)
- Java SE version (8 or 11)

**Comment by jeyvison** [comment]
The API has versions 8.0 and 9.1 now. Maybe we shouldn´t consider 9.0 for our MVP?

**Comment by batashi** [comment]
Hi team, 
Did anyone start developing the UI for this project? any prototype I want participates if possible.

Regards

**Comment by m-reza-rahman** [comment]
Not yet, but you could get started if you like?

If you are OK to do that, can you kindly start a discussion on the mailing list: https://accounts.eclipse.org/mailing-list/starter-dev?

We need to decide on what UI technology to use and also how to set up infrastructure.

Thanks!

**Comment by IvoNet** [comment]
I wouldn't mind working with y'all on this and see if we can join efforts...

I have maintained a working version for a couple of years now and and fully prepared to "donate" it to the community.

[https://ivonet.github.io/archetype/](https://ivonet.github.io/archetype/) is where I maintain a couple of maven archetypes the way @ivargrimstad described above.

**Comment by m-reza-rahman** [comment]
Are you referring to a UI or a merge generally? Either way, this is probably too involved of a discussion for a specific GitHub issue. Maybe start a mailing list thread?

**Comment by IvoNet** [comment]
I've moved the discussion to the mailing list :-)

**Comment by hantsy** [comment]
@ivargrimstad Additional user input:
 
* Java version: 8, 11, 17, and the latest GA(now is 18) when selecting a Jakarta EE version, show a compatible label.
* Runtime: (Glassfish/Payara/WildFly/OpenLibtery, Micro Payara, Embedded/Modular Wildfly(to package app into a single jar), Dockerized application server, K8s ready config for supported application server etc)

**Comment by m-reza-rahman** [comment]
I would say the best thing would be to issue PRs for the things you would like to see instead of waiting for someone else to do it. Sounds like much of it should be doable already based on what is currently on the main branch?

**Comment by m-reza-rahman** [comment]
[rokon12](https://github.com/rokon12) is working on this.

**Comment by m-reza-rahman** [comment]
I think this should have been discussed a bit before being closed. As indicated here and discussed in the mailing list, @rokon12 is working on this based on the approach already agreed upon and I have secured hosting from Microsoft as I let @ivargrimstad some time ago.
