### ISSUE TITLE
Failed to pass tests with Java 18

### ISSUE THREAD

**Issue by hakdogan** [eclipse-ee4j/starter#95]
I'm using openjdk version "18" 2022-03-22

The tests are not passed when I executed `mvn clean package`.
 
> [] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1649422042721] [levelValue: 1000] Unsupported class file major version 62
> ...
> java.lang.IllegalArgumentException: ArquillianServletRunner not found. Could not determine ContextRoot from ProtocolMetadata, please contact DeployableContainer developer.

Also, the project wasn't deployed successfully when executed `mvn clean package payara-micro:start`

**Comment by m-reza-rahman** [comment]
I don’t think Payara 5 works with Java SE 18. However, I will confirm and update the docs. I do know for sure Java SE 8 and 11 should work.

**Comment by hakdogan** [comment]
Hi @m-reza-rahman,

You're right, I didn't have any problems with Java 17

**Comment by m-reza-rahman** [comment]
OK. I’ll tweak the documentation to state that we tested 8, 11 and 17.
